version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: evolveai_postgres
    restart: always
    environment:
      POSTGRES_USER: evolveai_user
      POSTGRES_PASSWORD: evolveai_password
      POSTGRES_DB: evolveai_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolve-network

  redis:
    image: redis:latest
    container_name: evolveai_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - evolve-network

networks:
  evolve-network:

volumes:
  postgres_data:
