events {}

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;

  server {
    listen 80;
    server_name evolve.ai;

    location / {
      root /usr/share/nginx/html/main;
      index index.html;
      try_files $uri /index.html;
    }

    location /api/auth/ {
      proxy_pass http://auth-service:8001;
    }

    location /api/teacher/ {
      proxy_pass http://teacher-service:8005;
    }

    location /api/student/ {
      proxy_pass http://student-service:8090;
    }
  }

  server {
    listen 80;
    server_name teacher.evolve.ai;

    location / {
      root /usr/share/nginx/html/teacher;
      index index.html;
      try_files $uri /index.html;
    }
  }

  server {
    listen 80;
    server_name student.evolve.ai;

    location / {
      root /usr/share/nginx/html/student;
      index index.html;
      try_files $uri /index.html;
    }
  }

  server {
    listen 80;
    server_name exam.evolve.ai;

    location / {
      root /usr/share/nginx/html/exam;
      index index.html;
      try_files $uri /index.html;
    }
  }
}
