packages:
  - "backend-service/api-gateway"
  - "backend-service/auth-service"
  - "backend-service/teacher-service"
  - "backend-service/student-service"
  - "backend-service/notification-service"
  - "backend-service/exam-service"
  - "Evolve-Student"
  - "Evolve-Teacher"
  - "Evolve-Exam"
