// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suceqmutyqugtcojrecd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y2VxbXV0eXF1Z3Rjb2pyZWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTMwMDEsImV4cCI6MjA1NzkyOTAwMX0.k-4cpMMqv3FhyP7knG-Vs_VUIMBXjC5FKihlpPryWsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);