import mongoose from "mongoose";
import dotenv from "dotenv";
import Assignment from "../models/assignmentModel.js"; // Adjust if needed
import axios from "axios";

dotenv.config();

// Generate randomized sample assignments (15 records, dueDate <= today)
const randomPastDate = (maxDaysBack = 45) => {
  const now = Date.now();
  const days = Math.floor(Math.random() * (maxDaysBack + 1));
  const hours = Math.floor(Math.random() * 24);
  const minutes = Math.floor(Math.random() * 60);
  return new Date(now - ((days * 24 + hours) * 60 + minutes) * 60 * 1000);
};

const submissionTypes = ["FILE", "TEXT", "CODE"];
const statuses = ["PUBLISHED", "DRAFT", "CLOSED"];

const seedDB = async () => {
  try {
    const AUTH_SERVICE_URL = process.env.AUTH_SERVICE_URL || "http://localhost:8001";
    const { data: subjects } = await axios.get(`${AUTH_SERVICE_URL}/subjects`);
    const courses = (subjects || []).map((s) => (s?.code || s?.name || "GEN").toString().toLowerCase());
    const courseList = courses.length > 0 ? courses : ["cs101", "cs201", "cs301"]; // fallback

    const assignments = Array.from({ length: 15 }).map((_, i) => {
      const course = courseList[i % courseList.length];
      const useAI = Math.random() < 0.5;
      const submissionType = submissionTypes[i % submissionTypes.length];
      const status = statuses[i % statuses.length];
      return {
        title: `Auto Assignment #${i + 1}`,
        description: `Autogenerated assignment ${i + 1} for ${course}.`,
        dueDate: randomPastDate(45),
        teacherId: i % 5 === 0 ? "660b123456789abcd0123458" : "660b123456789abcd0123456",
        course,
        useAI,
        submissionType,
        status,
        materials: `https://res.cloudinary.com/demo/image/upload/v1710000000/assignments/auto_${i + 1}.pdf`,
      };
    });
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });

    console.log("🚀 Connected to MongoDB...");

    // Clear existing assignments
    await Assignment.deleteMany();
    console.log("🗑️ Removed old assignments.");

    // Insert new assignments
    await Assignment.insertMany(assignments);
    console.log(`✅ ${assignments.length} Assignments added successfully (subjects sourced from auth-service).`);

    mongoose.connection.close();
  } catch (error) {
    console.error("❌ Error seeding data:", error);
    mongoose.connection.close();
  }
};

seedDB();
